version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - d:/gn.legal/data/mongodb-security:/data/db
  
  mongo-express:
      image: mongo-express
      restart: unless-stopped
      ports: 
          - 8081:8081
      volumes: 
          - d:/gn.legal/data/mongo-express:/data/db
      environment:
        ME_CONFIG_MONGODB_URL: mongodb://$MONGODBUSER:$MONGODBPASSWORD@mongo:27017/
        ME_CONFIG_MONGODB_ENABLE_ADMIN: true
        ME_CONFIG_BASICAUTH: true
        ME_CONFIG_BASICAUTH_USERNAME: $ME_CONFIG_BASICAUTH_USERNAME
        ME_CONFIG_BASICAUTH_PASSWORD: $ME_CONFIG_BASICAUTH_PASSWORD

  app:
    depends_on:
      - mongodb
      - mongo-express
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      DB_HOST: mongodb
      DB_USER: $MONGODB_USER
      DB_PASSWORD: $MONGODB_PASSWORD
      DB_NAME: $MONGODB_DATABASE
      DB_PORT: $MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db: